.TH CLONKY 1 "August 30, 2012" "version 0.2" "USER COMMANDS"
.SH NAME
clonky \- a tiny X11 reminder for the command line
.SH DESCRIPTION
You always miss your important meetings? Or you occasionally forget to go home? clonky can help you.
.PP
At alarm time a xmessage window will popup reminding you about something.
.SH OPTIONS
.TP
HOURS
set the hour
.TP
[MINUTES]\-optional
set the minutes
.TP
[MESSAGE]\-optional
set the messsage at display time
.SH EXAMPLES
.TP
Set clonky to remind you at 09.30:
.B clonky
09 30
.PP
.SH EXIT STATUS
clonky displays a message "Setting alarm clock to 12:00"
.SH AUTHOR
Maximilian Meister (mmeister@suse.de)
.PP
Johannes Meixner (jsmeix@suse.de)
